**Numpy: Numeric computing library**

NumPy (Numerical Python) is one of the core packages for numerical computing in Python. Pandas, Matplotlib, Statmodels and many other Scientific libraries rely on NumPy.


In [1]:
import sys
import numpy as np

**Basic numpy arrays**

In [3]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [4]:
a= np.array([1, 2, 3, 4])

In [5]:
a

array([1, 2, 3, 4])

In [13]:
b = np.array([0, .5, 1, 1.5, 2])
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [6]:
a[0],a[1]

(1, 2)

In [7]:
a[0:1]

array([1])

In [8]:
a[:1]

array([1])

In [9]:
a[2:]

array([3, 4])

In [10]:
a[: :]

array([1, 2, 3, 4])

In [11]:
a[:-1]

array([1, 2, 3])

**Array Types**

In [16]:
a.dtype

dtype('int32')

In [17]:
b.dtype

dtype('float64')

In [18]:
np.array([1, 2, 3, 4], dtype=np.float)

array([1., 2., 3., 4.])

In [19]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [20]:
c = np.array(['a', 'b', 'c'])

In [21]:
c.dtype

dtype('<U1')

In [22]:
d = np.array([{'a': 1}, sys])

In [23]:
d.dtype

dtype('O')

**Dimensions and shapes**

In [24]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]])

In [25]:
A.dtype

dtype('int32')

In [26]:
A.shape

(2, 3)

In [27]:
A.size

6

In [28]:
A.ndim

2

In [29]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [30]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
B.size

12

In [32]:
B.shape

(2, 2, 3)

In [33]:
B.ndim

3

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [34]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

<ipython-input-34-39b57e6bbad9>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  C = np.array([


In [35]:
C.dtype

dtype('O')

In [36]:
C.shape

(2,)

In [37]:
C.size

2

In [38]:
type(C[0])

list

**Indexing and Slicing of Matrices**

In [40]:
# Square matrix
A = np.array([
    [1, 2, 3], # 0
    [4, 5, 6], # 1
    [7, 8, 9]  # 2
])

In [41]:
A[1]

array([4, 5, 6])

In [42]:
A[1][0]

4

In [43]:
A[1,2]

6

In [44]:
A[1:0]

array([], shape=(0, 3), dtype=int32)

In [45]:
A[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
A[::]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
A[:-1]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
A[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [50]:
A[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
A[:0]

array([], shape=(0, 3), dtype=int32)

In [52]:
A[1] = np.array([10, 10, 10])

In [53]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [54]:
A[2]=88

In [55]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [88, 88, 88]])

**Summary Statistics**

In [56]:
a.sum()

10

In [57]:
a.std()

1.118033988749895

In [58]:
a.var()

1.25

In [62]:
a.mean()

2.5

In [63]:
A.sum()

300

In [64]:
A.mean()

33.333333333333336

In [65]:
A.std()

38.7957615096174

In [66]:
A.var()

1505.111111111111

In [68]:
A.sum(axis=1)

array([  6,  30, 264])

In [69]:
A.mean(axis=1)

array([ 2., 10., 88.])

In [70]:
A.std(axis=1)

array([0.81649658, 0.        , 0.        ])

In [71]:
A.var(axis=1)

array([0.66666667, 0.        , 0.        ])

**Broadcasting and Vectorized operations**

In [73]:
a = np.arange(4)

In [74]:
a

array([0, 1, 2, 3])

In [75]:
a+10

array([10, 11, 12, 13])

In [76]:
a-10

array([-10,  -9,  -8,  -7])

In [77]:
a*10

array([ 0, 10, 20, 30])

In [80]:
a += 100
a

array([300, 301, 302, 303])

In [81]:
l = [0, 1, 2, 3]
[i * 10 for i in l]

[0, 10, 20, 30]

In [82]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [83]:
b = np.array([10, 10, 10, 10])
b

array([10, 10, 10, 10])

In [84]:
a+b

array([10, 11, 12, 13])

In [85]:
a*b

array([ 0, 10, 20, 30])

**Boolean arrays**

In [87]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [88]:
a[0],a[-1]

(0, 3)

In [90]:
a[[0,-1]]

array([0, 3])

In [91]:
a[[True, False, False, True]]

array([0, 3])

In [92]:
a >= 2

array([False, False,  True,  True])

In [93]:
a[a>=2]

array([2, 3])

In [94]:
a.mean()

1.5

In [95]:
a[a > a.mean()]

array([2, 3])

In [96]:
a[~(a > a.mean())]

array([0, 1])

In [97]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [98]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [99]:
A = np.random.randint(100, size=(3, 3))
A

array([[83, 42, 29],
       [87,  3,  3],
       [95, 65, 30]])

In [100]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([83, 29,  3, 95, 30])

In [101]:
A>30

array([[ True,  True, False],
       [ True, False, False],
       [ True,  True, False]])

In [102]:
A[A>30]

array([83, 42, 87, 95, 65])

**Linear Algebra**

In [103]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [104]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [105]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [106]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [108]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

In [109]:
B.T@A

array([[36, 48, 60],
       [24, 33, 42]])

**Size of objects in Memory**
 Int, floats

In [110]:
# An integer in Python is > 24bytes
sys.getsizeof(1)

28

In [111]:
# Longs are even larger
sys.getsizeof(10**100)

72

In [112]:
# Numpy size is much smaller
np.dtype(int).itemsize

4

In [113]:
# Numpy size is much smaller
np.dtype(np.int8).itemsize

1

In [114]:
np.dtype(float).itemsize


8

**Lists are even larger**

In [115]:
# A one-element list
sys.getsizeof([1])

64

In [116]:
# An array of one element in numpy
np.array([1]).nbytes

4

**And performance is also important**

In [117]:
l = list(range(100000))
a = np.arange(100000)
%time np.sum(a ** 2)

Wall time: 924 µs


216474736

In [118]:
%time sum([x ** 2 for x in l])

Wall time: 62.3 ms


333328333350000

**Useful numpy functions**

random

In [120]:
np.random.random(size=2)

array([0.74825756, 0.93450607])

In [121]:
np.random.normal(size=2)

array([-0.41350984,  0.70281866])

In [122]:
np.random.rand(2, 4)

array([[0.12096507, 0.10456037, 0.78727658, 0.40665346],
       [0.59253123, 0.38312755, 0.86004097, 0.15006302]])

arange

In [123]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [125]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

reshape

In [126]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [127]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

linspace

In [128]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [129]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [130]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

zeros, ones, empty

In [131]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [132]:
np.zeros((3, 3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [133]:
np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [134]:
np.ones(5)


array([1., 1., 1., 1., 1.])

In [135]:
np.ones((3, 3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [136]:
np.empty(5)


array([1., 1., 1., 1., 1.])

In [137]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

identity and eye

In [138]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [139]:
np.eye(3, 3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [140]:
np.eye(8, 4)


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [141]:
np.eye(8, 4, k=1)


array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [142]:
np.eye(8, 4, k=-3)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [143]:
"Hello World"[6]

'W'